# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

a = np.array([1,2,6])
b = np.array([4,5,6])
print(a)
print(b)

print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))