# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

print("Test if two arrays are element-wise equal within a tolerance:")

# Checking if the two arrays are element-wise equal within a tolerance and printing the result
# a = [1e10, 1e-7], b = [1.00001e10, 1e-8]
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-9], [1.0001e10,1e-9]))

# Checking if the arrays with NaN (Not a Number) values are equal while treating NaN as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
# NaN != NaN always

# use equal_nan=True
# Checking if the arrays with NaN (Not a Number) values are equal considering NaN values as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

