# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

a = np.array([1+0j, 1+1j, 2.5, 3, 2j])
print("Original array: ", a)

print("Checking for complex number :", np.iscomplex(a))
print("Checking for real number :", np.isreal(a))
print("Checking for scalar type: ", np.isscalar(3.1))
print("Checking if [3.1] is a scalar or not: ", np.isscalar([3.1]))