# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

a = np.array([-1,-2, np.inf, -np.inf, 0, 3.5])
a

result_pos_inf = np.isposinf(a)
result_neg_inf = np.isneginf(a)

print(result_pos_inf)
print(result_neg_inf)