# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

a = np.array([0,1,2,3])
print(" original array:")
print(a)

print("Test whether any of the elements of a given array is non-zero:")
print(np.any(a))

a = np.array([0, 0, 0, 0])
print("Original array:")
print(a)

print("Test whether any of the elements of a given array is non-zero:")
print(np.any(a))
