# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

a = np.array([1, 0, np.nan, np.inf])

print("Original array")
print(a)

print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))