# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GJxKQKzdxk1pdiGtZ9SgZTzoUmkdnQB
"""

import numpy as np

a = np.array([1,2,3,4])
print("Original array: ")
print(a)

print("Test if none of the elements of the said array is zero:")
print(np.all(a))

a = np.array([0,1,2,3])
print("Original array: ")
print(a)

print("Test if none of the elements of the said array is zero:")
print(np.all(a))